config/routes.rb
Jash2012::Application.routes.draw do
  resources :guests do
    collection do
         get 'list'
      end
  end

   root :to => 'guests#new'

end

app/models/guest.rb
class Guest < ActiveRecord::Base
	attr_accessible :attending, :cell_num, :name ,:sex ,:email_id
	validates_with JashnFunkyMessageValidator
	validates :email_id, presence: true
	validates :email_id , format: {with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/, message: "is inValid"}
	scope :attending , -> {where(attending: true)}
	class << self
		def assign_name_and_avatar size 
			change_dir_for_avatars size
			data =  attending
 			male_avatars, female_avatars = Dir.glob('m_*.jpg'), Dir.glob('f_*.jpg')
			get_male_female_avatars male_avatars , female_avatars , data.shuffle
		end

		def get_male_female_avatars male_avatars , female_avatars , data
			hsh =  HashWithIndifferentAccess.new
			md = male_avatar_details ({male_avatars: male_avatars ,
											   hash: hsh ,
				    					   	   data: data} )

			fd =  female_avatar_details ({female_avatars: female_avatars ,
													hash: hsh ,
												    data: data})
			(md + fd).shuffle
		end

		def list
			assign_name_and_avatar('resized').each_slice(4).to_a
		end

		def male_avatar_details opts = {}
			hsh = opts[:hash]
			hsh[:male]  = Array.new   
			male_data = opts[:data].select {|data| data.sex == 'male'}
			male_data.each {|dt| hsh[:male]<< [dt.name,opts[:male_avatars].sample]}
			hsh[:male]
		end
        
        def female_avatar_details opts = {}
			hsh = opts[:hash]
			hsh[:female]  = Array.new  
			female_data = opts[:data].select {|data| data.sex == 'female'}
			female_data.each {|dt| hsh[:female] << [dt.name,opts[:female_avatars].sample]}
			hsh[:female]
		end

		def change_dir_for_avatars size
			begin
				case size
				when 'original'
					Dir.chdir('app/assets/images')
				when 'resized' 
					Dir.chdir('app/assets/images/resized')	
				end 	
			rescue
				Dir
			end
		end

		

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  # GET /guests
  # GET /guests.json
  http_basic_authenticate_with :name => AUTH_CONFIG['credentials']['username'] ,:password => AUTH_CONFIG['credentials']['password'], :except => [:new,:show,:create,:list]
  def index
    @guests = Guest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guests }
    end
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
    @guest = Guest.find(params[:id])
    @guests = Guest.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @guest }
    end
  end

  # GET /guests/new
  # GET /guests/new.json
  def new
    @guest = Guest.new
    @guests = Guest.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guest }
    end
  end

  # GET /guests/1/edit
  def edit
    @guest = Guest.find(params[:id])
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(params[:guest])
    respond_to do |format|
      if verify_captcha(@guest) &&  @guest.save 
        #deliver_mail(@guest)
        format.html { redirect_to @guest, notice: "We have been Notified.  Thank you ! Please find the complete list of attendes #{view_context.link_to('here', list_guests_url, target: '_blank') }.".html_safe}
        format.json { render json: @guest, status: :created, location: @guest }
      else
        format.html { render action: "new" }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /guests/1
  # PUT /guests/1.json
  def update
    @guest = Guest.find(params[:id])

    respond_to do |format|
      if @guest.update_attributes(params[:guest])
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def list
   @guests = Guest.list
   render :layout => 'guest_list'
 end
  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy

    respond_to do |format|
      format.html { redirect_to guests_url }
      format.json { head :no_content }
    end
  end
end



def deliver_mail guest
  case guest.attending
  when true
    GuestMailer.send_to_attending(@guest).deliver
  when false
    GuestMailer.send_to_not_attending(@guest).deliver 
  end
end


private

def verify_captcha guest
  verify_recaptcha(:model => guest, :message => "Oh! It's error with reCAPTCHA!" ,:private_key => AUTH_CONFIG['recaptcha']['private_key'])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
	
	def formatted_message arr
		str = 'Sorry! Your '
		a = Array.new
		arr.each do |msg|
			a <<  msg.split(' ')[0]
		end
		(str + a.join(', ') + ' is Missing ').html_safe
	end

	def get_attendees 
		Guest.assign_name_and_avatar('original')
	end

	def formatted_name name
		['Awesome', 'Woahhh', 'Ahaaaaa..', 'Cool','Beautiful', 'Amazing','Alarming','Beware','Stupendous','Excellent'].sample + '...   ' + name.capitalize + " is Attending "
	end

	def formatted_guest_list name
		str = name.capitalize + "<br> is Attending "
		str.html_safe
	end
	
	def image arr
		arr ? "resized/#{arr[1]}" : 'resized/default_avatar.jpg'
	end

	def formatted_count
		Guest.attending.count.to_s + " Attending"
	end

	def guests_attending 
		Guest.attending.pluck(:name)		
	end
end

app/views/guests/_form.html.erb
<%= form_for @guest  do |f| %>
<% unless @guest.errors.full_messages.blank? %>
<div class="alert alert-error">
	<%= @guest.errors.full_messages.first %> <i class='icon-off'></i>
</div>
<%end%>

<div class="input-prepend input-append">
	<span class="add-on">N</span>
	<%= f.text_field :name ,:size => 40,:placeholder => 'Name' %>
</div>

<div class="input-prepend input-append">
	<span class="add-on"><i class='icon-signal'></i></span>
	<%= f.phone_field :cell_num ,:placeholder => 'Mobile No '%>
</div>
<div class="input-prepend input-append">
	<span class="add-on">@</span>
	<%= f.text_field :email_id ,:size => 40,:placeholder => 'Email' %> 
</div>

<label class="radio inline">
	<%= f.radio_button :sex, "male" %> Male
</label>
<label class="radio inline">
	<%= f.radio_button :sex, "female"  %> Female
</label>

<label class="checkbox">
	<%= f.check_box :attending%> Attending ?
</label>

<%= recaptcha_tags :public_key => AUTH_CONFIG['recaptcha']['public_key'] %> <br>
<%= f.submit 'Register',:class => 'btn btn-warning'%> 
<i id="example"  style="cursor: hand; cursor: pointer;"" rel="popover" data-content="We Highly recommend you to use Firefox or Chrome. " data-original-title="Browser Issues ?"class='icon-info-sign'></i>
<% end %>
<script type="text/javascript">
	$('#example').popover();

</script>

app/views/guests/edit.html.erb
<h1>Editing guest</h1>

<%= render 'form' %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<h1>Listing guests</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Cell num</th>
    <th>Attending</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guests.each do |guest| %>
  <tr>
    <td><%= guest.name %></td>
    <td><%= guest.cell_num %></td>
    <td><%= guest.attending %></td>
    <td><%= link_to 'Show', guest %></td>
    <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
    <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guest', new_guest_path %>

app/views/guests/list.html.erb
<div class="page-header">
  <h1>Our Guest List <i class='icon-star'></i><i class='icon-star'></i><i class='icon-star'></i> <small><%= formatted_count %></small></h1>
</div>
<table class="table table-hover">
  <% for guest_arr in @guests %>
  <tr>
    <td> <%= image_tag image(guest_arr[0]) ,class: 'img-polaroid' %></td>
    <td> <%= image_tag image(guest_arr[1]), class: 'img-polaroid' %></td>
    <td> <%= image_tag image(guest_arr[2]) ,class: 'img-polaroid' %></td>
    <td> <%= image_tag image(guest_arr[3]),class: 'img-polaroid' %></td>
  </tr>
  <tr>
    <td> <strong><%= guest_arr[0] ? formatted_guest_list(guest_arr[0][0]) : 'It can be you!!' %><i class='icon-ok'></i></strong></td>
    <td> <strong><%= guest_arr[1] ? formatted_guest_list(guest_arr[1][0]) : 'It can be you!!'%><i class='icon-ok'></i></strong></td>
    <td> <strong><%= guest_arr[2] ? formatted_guest_list(guest_arr[2][0]) : 'It can be you!!'%><i class='icon-ok'></i></strong></td>
    <td> <strong><%= guest_arr[3] ? formatted_guest_list(guest_arr[3][0]) : 'It can be you!!'%><i class='icon-ok'></i></td>
  </tr>
  <% end %>
</table>

app/views/guests/new.html.erb
<h3>You are Special  <i class="icon-thumbs-up"></i></h3>
<p class="lead">Get on our Guest List</p>

<%= render 'form' %>

app/views/guests/show.html.erb
<div class="alert alert-success">
 <p id="notice"><%= notice %> </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Jashn 2012</title>
	<%= favicon_link_tag 'favicon.ico' %>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= render 'shared/top_carousel' %>
		<div class="row">
			<div class="span4">	
				<%= yield %>
			</div>
			<%= render 'shared/right_panel', :guests => @guests %>
	</div>
	
	
</body>
</html>

app/views/layouts/guest_list.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Jashn 2012</title>
	<%= favicon_link_tag 'favicon.ico' %>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="span2">
			</div>
			<div class="span8">
				<%= yield %>
				<%= render 'shared/footer' %>
			</div>
		</div>

	</div>

</body>
</html>

app/views/shared/_attendee.html.erb
<!--  Carousel - consult the Twitter Bootstrap docs at 
  http://twitter.github.com/bootstrap/javascript.html#carousel -->
  <h3>Our Guests <%= link_to 'Check guest list', list_guests_url , role: 'button' , class: 'label label-warning' ,rel: 'tooltip' ,id: 'element' ,target: '_blank' %><i class="icon-user"> </i></h3>
  <div id="attendee-carousel-id" class="carousel slide"><!-- class of slide for animation -->
    <div class="carousel-inner">
     <!-- class of active since it's the first item -->
     <% for attendee in get_attendees %>
       <div class="item">
        <%= image_tag attendee[1] %>
        <div class="carousel-caption">
        <p ><small> <%= formatted_name attendee[0] %> <i class='icon-glass icon-white'></i> </small></p>
      </div>
    </div>
    <% end %>
 </div><!-- /.carousel-inner -->
  <!--  Next and Previous controls below
  href values must reference the id for this carousel -->
</div><!-- /.carousel -->
<script type="text/javascript">
$('#attendee-carousel-id').carousel({
  interval: 1500
})

$('#element').tooltip({
  placement : 'right',
  animation : true
});
</script>

app/views/shared/_attending.html.erb
<table class="table" id='source'>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% for guest_name in guests_attending %>
        <td>
          <i class='icon-ok' style="margin-right:5px"></i>
          <%= guest_name -%>
        </td>
      <% end %>
    </tr>
  </tbody>
</table>
<table id="des"></table>
<script type="text/javascript">
$(function(){
  while($("#source td").length > 0){
    $("#des").append($("<tr/>").append($("#source td").slice(0, 4)));
  }
  $("#source").remove(); 
});
</script>

app/views/shared/_attending_list.html.erb
<div aria-hidden="false" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" class="modal hide fade in" id="myModal">
	<button style="margin-right: 10px" aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
	
	<div class="modal-body" style="background-color: #FFFAEF;">
		<%= render 'shared/attending' %>
	</div>

</div>

app/views/shared/_footer.html.erb
<blockquote>
  <p class='text-warning'>Designed and Developed by </p>
  <small> <%= link_to 'Ankit Gupta', 'http://github.com/ankit8898' , {class: 'text-warning', target: '_blank'}%> |
   <cite title="Source Title"><%= link_to 'Ashish Upadhyay' ,'http://rorashish.blogspot.com' ,{class: 'text-warning', target: '_blank'}%></cite> | <cite title="Source Title"><%= link_to 'Manasi Kshatriya' ,"JavaScript:void(0);", {class: 'text-warning'}%></cite></small>
</blockquote>

app/views/shared/_right_panel.html.erb
<div class="span4">
	<%= render 'shared/attendee' %>  
	<%= render 'shared/footer' %>
</div>
<div class="span4">
	<h3>28th December, 2012  <i class="icon-calendar"></i></h3>
	<address>
		
		<strong>360° Degree Restaurant</strong><br>
		1st Floor, Home Town, 247 Park, <br>
		LBS Marg, Vikhroli, Mumbai<br>
		<p class='text-warning'>Phone: 022 61775253 </p>
		<iframe width="250" height="120" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=d&amp;source=s_d&amp;saddr=Kensington+B+Wing+-+TATA+Consultancy+Services,+Powai,+Maharashtra,+India&amp;daddr=Hometown,+247+Park,+Hincon+House,+-400083,+Lal+Bahadur+Shastri+Road,+Vikhroli+West,+MH,+India&amp;hl=en&amp;geocode=FaegIwEdsIhYBCE6dyR7b-ikUykDFIYP6MfnOzE6dyR7b-ikUw%3BFc7AIwEd9sVYBCkLaNq4k8fnOzH18DLppfQOmg&amp;aq=1&amp;oq=kensin&amp;sll=19.122179,72.92613&amp;sspn=0.022544,0.038495&amp;mra=ls&amp;ie=UTF8&amp;ll=19.122179,72.92613&amp;spn=0.01677,0.01747&amp;t=m&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com/maps?f=d&amp;source=embed&amp;saddr=Kensington+B+Wing+-+TATA+Consultancy+Services,+Powai,+Maharashtra,+India&amp;daddr=Hometown,+247+Park,+Hincon+House,+-400083,+Lal+Bahadur+Shastri+Road,+Vikhroli+West,+MH,+India&amp;hl=en&amp;geocode=FaegIwEdsIhYBCE6dyR7b-ikUykDFIYP6MfnOzE6dyR7b-ikUw%3BFc7AIwEd9sVYBCkLaNq4k8fnOzH18DLppfQOmg&amp;aq=1&amp;oq=kensin&amp;sll=19.122179,72.92613&amp;sspn=0.022544,0.038495&amp;mra=ls&amp;ie=UTF8&amp;ll=19.122179,72.92613&amp;spn=0.01677,0.01747&amp;t=m" style="text-align:left" target="_blank;"  class='text-warning'><p  class='text-warning'>View Larger Map</p></a></small>

	</address>

	<address>
		<strong>Contact: Ankit Gupta</strong><br>
		<p class='text-warning'>Phone: 91 9004408181 </p>
	</address>
</div>
</div>
<%= render 'shared/attending_list' %>

app/views/shared/_top_carousel.html.erb
<!--  Carousel - consult the Twitter Bootstrap docs at 
  http://twitter.github.com/bootstrap/javascript.html#carousel -->
  <div id="this-carousel-id" class="carousel slide"><!-- class of slide for animation -->
    <div class="carousel-inner">
      <div class="item active"><!-- class of active since it's the first item -->
        <%= image_tag 'siteimg1.jpg' %>
      </div>
      <div class="item">
       <%= image_tag 'siteimg2.jpg' %>
       <div class="carousel-caption">
        <p class="lead">Rhythm of voice !</p>
        <p>
         <small>Clear up your vocal chords to mesmerize the audience with your melodious voice.</small>
    </p>
      </div>
    </div>
    <div class="item">
     <%= image_tag 'siteimg3.jpg' %>
     <div class="carousel-caption">
      <p class='lead'>Race with the Beats, a Peacock or a Sheep !</p>
      <p>
         <small>Unleash the hidden dance in you and get ready to rock the dance floor.</small>
    </p>
    </div>
  </div>
  <div class="item">
    <%= image_tag 'siteimg4.jpg' %>
    <div class="carousel-caption">
      <p class='lead'>All work and No play makes Jack a dull Boy.</p>
      <p>
         <small>Let's see the challenging kid inside you.</small>
    </p>
    </div>
  </div>
  <div class="item">
    <%= image_tag 'siteimg5.jpg' %>
    <div class="carousel-caption">
       <p class='lead'>To know if you are mad enough to be creative !</p>
       <p>
         <small>Put on your acting masks and advertise yourself.</small>
    </p>
    </div>
  </div>
  <div class="item">
    <%= image_tag 'siteimg6.jpg' %>
    <div class="carousel-caption">
      <p class='lead'>Showcasing what's 'In' and what's not !</p>
      <p>
         <small>All the Software Geeks.  It's time to rethink your career in Modelling.</small>
    </p>
    </div>
  </div>
  <div class="item">
    <%= image_tag 'siteimg7.jpg' %>
    <div class="carousel-caption">
       <p class='lead'>Discover the 'Holmes' in you !</p>
       <p>
         <small>Look for it and win it.. The Ultimate Treasure.</small>
    </p>
    </div>
  </div>
  <div class="item">
    <%= image_tag 'siteimg8.jpg' %>
    <div class="carousel-caption">
       <p class='lead'>Workplace can be beautiful !</p>
       <p>
         <small>Who said workplace is just to work, Let's design it in our way.</small>
    </p>
    </div>
  </div>
</div><!-- /.carousel-inner -->
  <!--  Next and Previous controls below
  href values must reference the id for this carousel -->
  <a class="carousel-control left" href="#this-carousel-id" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#this-carousel-id" data-slide="next">&rsaquo;</a>
</div><!-- /.carousel -->
<script type="text/javascript">
$('#this-carousel-id').carousel({
  interval: 6000
})
</script>

app/views/shared/_top_nav.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Jashn 2012</a>
      <div class="nav-collapse">
        <ul class="nav">
          
        </ul>
      </div>
    </div>
  </div>
</div>